package com.linguabridge.app.data.db.content

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase

@Database(
    entities = [
        VocabEntity::class,
        GrammarTermEntity::class,
        StemTermEntity::class,
        HskWordEntity::class,
        HskGrammarEntity::class,
        ReadingTextEntity::class,
        DialogueEntity::class,
        DialogueLineEntity::class,
        QuizQuestionEntity::class,
        ListeningPassageEntity::class,
        CardEntity::class
    ],
    version = 2,
    exportSchema = true
)
abstract class ContentDatabase : RoomDatabase() {

    abstract fun vocabDao(): VocabDao
    abstract fun cardDao(): CardDao
    abstract fun readingTextDao(): ReadingTextDao
    abstract fun dialogueDao(): DialogueDao
    abstract fun quizDao(): QuizDao
    abstract fun grammarTermDao(): GrammarTermDao
    abstract fun stemTermDao(): StemTermDao
    abstract fun hskDao(): HskDao

    companion object {
        private const val DATABASE_NAME = "content.db"

        fun build(context: Context): ContentDatabase =
            Room.databaseBuilder(
                context.applicationContext,
                ContentDatabase::class.java,
                DATABASE_NAME
            )
                .createFromAsset(DATABASE_NAME)
                // Content is disposable: it is fully regenerated by the packer on every
                // content update, so a destructive fallback is safe and avoids hand-written
                // migrations for read-only shipped data.
                .fallbackToDestructiveMigration(dropAllTables = true)
                .build()
    }
}
